### ISSUE TITLE
Bug: cloud-init fails on image images:alpine/3.17

### ISSUE THREAD

**Issue by omani** [lxc/lxd#11195]
```
a1:~# tail -f /var/log/cloud-init.log
  File "/usr/lib/python3.10/site-packages/cloudinit/sources/DataSourceCloudSigma.py", line 14, in <module>
    from cloudinit.sources.helpers.cloudsigma import SERIAL_PORT, Cepko
    return self._get_data_source(existing=existing)
  File "/usr/lib/python3.10/site-packages/cloudinit/stages.py", line 325, in _get_data_source
    (ds, dsname) = sources.find_source(
  File "/usr/lib/python3.10/site-packages/cloudinit/sources/__init__.py", line 930, in find_source
    ds_list = list_sources(cfg_list, ds_deps, pkg_list)
  File "/usr/lib/python3.10/site-packages/cloudinit/sources/__init__.py", line 976, in list_sources
    m_locs, _looked_locs = importer.find_module(
  File "/usr/lib/python3.10/site-packages/cloudinit/importer.py", line 55, in find_module
    if _count_attrs(full_path, required_attrs) == len(required_attrs):
  File "/usr/lib/python3.10/site-packages/cloudinit/importer.py", line 26, in _count_attrs
    mod = importlib.import_module(module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/cloudinit/sources/DataSourceCloudSigma.py", line 14, in <module>
    from cloudinit.sources.helpers.cloudsigma import SERIAL_PORT, Cepko
  File "/usr/lib/python3.10/site-packages/cloudinit/sources/helpers/cloudsigma.py", line 25, in <module>
    import serial
ModuleNotFoundError: No module named 'serial'
------------------------------------------------------------
```

also `netifaces` is missing. and probably many more python modules are missing.

```
# lxc profile show ci_base
config:
  cloud-init.user-data: |
    #cloud-config
    package_upgrade: true
    packages:
      - bash
    users:
      - name: ansible
        group: users
        sudo: true
        ssh_authorized_keys:
          - ssh-ed25519 ****
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: ci_base
used_by:
- /1.0/instances/a1
```

`lxc launch images:alpine/3.17/cloud a1 --profile ci_base`

tested the same cloud-init configuration with images:alpine/3.16/cloud and it worked.

I know alpine/3.17 is pretty new on the linuxcontainers image server but I wonder if they are not being tested before they are released on the remote image server.

**Comment by monstermunchkin** [comment]
Fixed here https://github.com/lxc/lxc-ci/pull/664

**Comment by si458** [comment]
Hi, will this fix apply to ISO images?
ive tried the latest version of ISO 3.17.1,
installed `cloud-init` then rebooted and its still showing `ModuleNotFoundError: No module named 'serial'`
i have to manually install `py3-pyserial` and `py3-netifaces` first

**Comment by tomponline** [comment]
@monstermunchkin please can you take a look? Thanks

**Comment by monstermunchkin** [comment]
@si458 are you using `images:alpine/3.17/cloud`? If so, then `py3-pyserial` and `py3-netifaces` are already installed and there shouldn't be any issues. If you are using `images:alpine/3.17` then you need to install everything manually. This however is not an issue with LXD or our images.

**Comment by si458** [comment]
> @si458 are you using `images:alpine/3.17/cloud`? If so, then `py3-pyserial` and `py3-netifaces` are already installed and there shouldn't be any issues. If you are using `images:alpine/3.17` then you need to install everything manually. This however is not an issue with LXD or our images.

sorry ive just realised, im talking about the alpine iso images directly, this repo is for LXC/LXD stuff! doh!
https://www.alpinelinux.org/downloads/
