### ISSUE TITLE
sudo with password broken inside container

### ISSUE THREAD

**Issue by tinix0** [lxc/lxd#1540]
After upgrading to version 0.27, sudo, when authenticating with password, stopped working inside all containers. I made no configuration changes from when it worked.
Error: sudo: no tty present and no askpass program specified
Host and Guest OS: Ubuntu 14.04

**Comment by stgraber** [comment]
```
ubuntu@abc:/root$ sudo -i
[sudo] password for ubuntu: 
root@abc:~# logout
```

That's through "lxc exec abc bash" on 0.27 with the host being 14.04 and the guest being 14.04.

**Comment by tinix0** [comment]
Does not work here, another thing that fails is ssh fails to ask for password when connecting to different server. And when ssh-ing into the container there is this line in the auth.log file:
sshd[13039]: error: open /dev/tty failed - could not set controlling tty: Operation not permitted
I can replicate this on all containers.

**Comment by stgraber** [comment]
What kernel are you running?

**Comment by tinix0** [comment]
Linux 3.19.0-47-generic #53~14.04.1-Ubuntu SMP Mon Jan 18 16:09:14 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by stgraber** [comment]
can you paste the output of "ls -lh /proc/self/fd"?

**Comment by stgraber** [comment]
from within lxc exec, that is

**Comment by tinix0** [comment]
total 0
lrwx------ 1 root root 64 Jan 26 22:43 0 -> /dev/pts/4
lrwx------ 1 root root 64 Jan 26 22:43 1 -> /dev/pts/4
lrwx------ 1 root root 64 Jan 26 22:43 2 -> /dev/pts/4
lrwx------ 1 root root 64 Jan 26 22:43 23 -> socket:[17729]
lr-x------ 1 root root 64 Jan 26 22:43 3 -> /proc/13133/fd
lrwx------ 1 root root 64 Jan 26 22:43 8 -> socket:[18717]

**Comment by stgraber** [comment]
lxc config show CONTAINER_NAME --expanded

**Comment by tinix0** [comment]
name: turing
profiles:
- base
config:
  boot.autostart: "true"
  limits.cpu: "6"
  limits.memory: 6GB
  security.privileged: "true"
  volatile.base_image: 35d3502192455effec7a12b43f532ff71812b14eb833818070dfd7b9e812d470
  volatile.eth0.hwaddr: 00:16:3e:a7:49:37
  volatile.eth1.hwaddr: 00:16:3e:8e:26:f9
  volatile.last_state.idmap: '[]'
devices:
  data:
    path: /data
    source: /data
    type: disk
  eth0:
    name: eth0
    nictype: bridged
    parent: br1
    type: nic
  eth1:
    name: eth1
    nictype: bridged
    parent: br2
    type: nic
  home:
    path: /home
    source: /home
    type: disk
  root:
    path: /
    type: disk
ephemeral: false

**Comment by stgraber** [comment]
ok, so that's a privileged container, that may explain why I can't reproduce it here.

**Comment by stgraber** [comment]
Indeed, there appears to be something going on with privileged containers.

**Comment by stgraber** [comment]
Figured it out, pushed a fix.

**Comment by tinix0** [comment]
Bug still occurs on lxd 2.0.0.beta1

**Comment by stgraber** [comment]
Did you restart the container after upgrading to lxd 2.0.0.beta1?

**Comment by tinix0** [comment]
Did stop / start , did not help. tried restart now but that DID help. Thanks.

**Comment by stgraber** [comment]
Hmm, that's weird, but okay. The change I pushed specifically changed the container config, so it does indeed require a full container restart to have it regenerated, simply restart lxd itself with the container running isn't enough.

**Comment by rfrei** [comment]
Bug still (or again?)  occurs on my machine. I have a new user 'localadmin' with password set in the container and can not execute sudo commands. With user 'ubuntu' without password it works.



lxc version:

```
rf@thinkpadsm:~$ lxc --version
2.0.5
```



kernel version:

```
rf@thinkpadsm:~$ uname -a
Linux thinkpadsm 4.4.0-45-lowlatency #66-Ubuntu SMP PREEMPT Wed Oct 19 14:57:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```



sudo as user 'ubuntu':

```
rf@thinkpadsm:~$ lxc exec rf-alfresco bash
root@rf-alfresco:~# su ubuntu
ubuntu@rf-alfresco:/root$ groups
ubuntu adm dialout cdrom floppy sudo audio dip video plugdev netdev lxd
ubuntu@rf-alfresco:/root$ sudo apt update
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
31 packages can be upgraded. Run 'apt list --upgradable' to see them.
ubuntu@rf-alfresco:/root$ exit
```



now as user 'localadmin':

```
root@rf-alfresco:~# su localadmin
localadmin@rf-alfresco:/root$ groups
localadmin adm dialout cdrom floppy sudo audio dip video plugdev netdev lxd
localadmin@rf-alfresco:/root$ sudo apt update
sudo: no tty present and no askpass program specified
```



ls -lh /proc/self/fd inside container:

```
localadmin@rf-alfresco:/root$ ls -lh /proc/self/fd
total 0
lrwx------ 1 localadmin localadmin 64 Oct 25 21:35 0 -> /dev/pts/8
lrwx------ 1 localadmin localadmin 64 Oct 25 21:35 1 -> /dev/pts/8
lrwx------ 1 localadmin localadmin 64 Oct 25 21:35 2 -> /dev/pts/8
lr-x------ 1 localadmin localadmin 64 Oct 25 21:35 3 -> /proc/731/fd
lrwx------ 1 localadmin localadmin 64 Oct 25 21:35 9 -> socket:[33834]
```



lxc config show rf-alfresco --expanded:

```
rf@thinkpadsm:~$ lxc config show rf-alfresco --expanded
name: rf-alfresco
profiles:
- default
config:
  volatile.base_image: 767a2bafeaef7cc7d140bbde9a0d598f3aa561f8313cc6b01bc4e9c991f85f56
  volatile.eth0.hwaddr: 00:16:3e:66:f5:e6
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":235536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":235536,"Nsid":0,"Maprange":65536}]'
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    type: disk
ephemeral: false
```

**Comment by stgraber** [comment]
@rfrei your container is unprivileged which means you're running into a completely different issue that's got to do with ttyname misbehaving in containers. @hallyn is tracking the fix for this with glibc upstream (it's taking quite a lot of time though).

**Comment by rfrei** [comment]
OK, thank you.

**Comment by pavlodvornikov** [comment]
Hello,

Is any updates on this ?

**Comment by stgraber** [comment]
The C library has been fixed upstream, but this may take a while for distributions to pick it up.

**Comment by pavlodvornikov** [comment]
Thank you.
