### ISSUE TITLE
USB pass-thought fails

### ISSUE THREAD

**Issue by haarts** [lxc/lxd#2556]
I'd like to use an LXD container to develop for Android. Keep it all nice and separated. 
I've started a privileged container (to share my code on the host machine with the client) and added an USB device. The device seems to show up on the container but is unusable.
# Steps to reproduce
1. Start a container (I've used Arch) `lxc launch images:archlinux my-container`
2. Make it a privileged container (not sure this is relevant). `lxc config set my-container security.privileged true`
3. Plugin a phone and figure out the vendorid and deviceid with `lsusb`. (BTW deviceid is required as opposed to what the docs say)
4. Observe that `/dev/bus/usb/xxx/yyy` now exists on the host and not the container
5. Add the device with: `lxc config device add my-container my-phone usb vendorid=18d1 productid=4e42`
6. Observe that `/dev/bus/usb/xxx/yyy` now exists on the container.
7. `cat /dev/bus/usb/xxx/yyy` on container yields `cat: /dev/bus/usb/xxx/yyy: No such device or address`

On the host: `ls -l /dev/bus/usb/xxx/yyy`:

```
crw-rw-r-- 1 root adbusers 189, 63 25 okt 11:41 /dev/bus/usb/001/062
```

On the container: `ls -l /dev/bus/usb/xxx/yyy`:

```
crw-rw---- 1 root root 61, 189 Oct 25 09:35 /dev/bus/usb/001/062
```

`lxc info`:

```
apiextensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: <snip>
  certificatefingerprint: 3a8c8b7e55185ec647323fbf95305f2ebb0e89077ccef844df68799551f57955
  driver: lxc
  driverversion: 2.0.4
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.19-1-lts-userns
  server: lxd
  serverpid: 22039
  serverversion: "2.1"
  storage: dir
  storageversion: ""
config: {}
public: false
```

`lxc info my-container`:

```
Name: my-container
Architecture: x86_64
Created: 2016/10/24 12:03 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 813
Ips:
  eth0: inet    10.202.80.247   veth4QLNRF
  eth0: inet6   fe80::216:3eff:fe2d:ec1a    veth4QLNRF
  lo:   inet    127.0.0.1
  lo:   inet6   ::1
Resources:
  Processes: 38
  Memory usage:
    Memory (current): 501.48MB
    Memory (peak): 746.71MB
  Network usage:
    eth0:
      <snip>
    lo:
      <snip>
```

`lxc config show my-container`:

```
name: my-container
profiles:
- default
config:
  security.privileged: "true"
  volatile.base_image: 260bc1f340935aa338b3b680e3b43b6c3a3d1f8d9cd46067598d28f5fadd1c1a
  volatile.eth0.hwaddr: 00:16:3e:2d:ec:1a
  volatile.last_state.idmap: '[]'
devices:
  my-phone:
    productid: "4e42"
    type: usb
    vendorid: 18d1
  root:
    path: /
    type: disk
  software:
    path: /root/source
    source: /home/harm/prj/my-source/
    type: disk
ephemeral: false
```

I'm at a loss here.

**Comment by brauner** [comment]
Can you try and reproduce this with current git master?

**Comment by haarts** [comment]
Certainly! I've tried with the newer 2.4.1 (from the archives) and now I get the same binary garbage as on the host. Win!
`adb` still doesn't work so I guess I'll try master next. But that's a little bit more work. Will report back.

**Comment by haarts** [comment]
The behavior is the same with master (which reports the same version 2.4.1).

**Comment by brauner** [comment]
I think the minor device number is wrong. That's why we might get that error.

**Comment by brauner** [comment]
I think I'll just give us our own little `Mknod()` that employs `makedev()` to correctly create the device number because I think this is what's causing the problem.

**Comment by stgraber** [comment]
Ok, so yeah we had some breakage in 2.1 for USB hotplug, this was fixed in 2.2 and higher and 2.4.1 certainly works for me here, I have adb and everything working properly in an unprivileged container.

**Comment by stgraber** [comment]
All that LXD does is create the /dev/bus/usb path in the container and make it read/write for the container. 

Looks like it did that fine for you, so any problem you get after that is more likely to come as an adb problem. That being said, last time I tried (a week or so ago), adb worked perfectly, at least when using the version of adb that's packaged in Ubuntu and that I installed in my unprivileged Ubuntu 16.04 container.

**Comment by haarts** [comment]
That is odd. I've just started an unprivileged Ubuntu 16.04 container and the issue persists. On the host I add the device with: ` lxc config device add my-container my-phone usb vendorid=2970 productid=201d`
It shows up on the other end but adb still won't list the devices (`adb devices`).

Is there a way to make sure it's not adb?

**Comment by stgraber** [comment]
Let me try here with my phone.

**Comment by stgraber** [comment]
```
stgraber@dakara:~/data/code/lxc/lxd (stgraber/master)$ lxc launch ubuntu:16.04 android
Creating android
Starting android

stgraber@dakara:~/data/code/lxc/lxd (stgraber/master)$ lsusb | grep -i sony
Bus 001 Device 009: ID 0fce:51da Sony Ericsson Mobile Communications AB

stgraber@dakara:~/data/code/lxc/lxd (stgraber/master)$ lxc config device add android z5c usb vendorid=0fce productid=51da
Device z5c added to android

stgraber@dakara:~/data/code/lxc/lxd (stgraber/master)$ lxc exec android bash
root@android:~# apt install android-tools-adb
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  android-tools-adb
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 68.2 kB of archives.
After this operation, 198 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 android-tools-adb amd64 5.1.1r36+git20160322-0ubuntu3 [68.2 kB]
Fetched 68.2 kB in 0s (318 kB/s)
Selecting previously unselected package android-tools-adb.
(Reading database ... 25464 files and directories currently installed.)
Preparing to unpack .../android-tools-adb_5.1.1r36+git20160322-0ubuntu3_amd64.deb ...
Unpacking android-tools-adb (5.1.1r36+git20160322-0ubuntu3) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up android-tools-adb (5.1.1r36+git20160322-0ubuntu3) ...

root@android:~# adb devices
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
List of devices attached
CB5A28TSU6      unauthorized

root@android:~# adb shell
shell@E5823:/ $
```

**Comment by stgraber** [comment]
I obviously had to enable adbd on my phone, have it unlocked and allow the fingerprint of my container to connect.

**Comment by fnjeneza** [comment]
I had the same issue previously. 
What i did was to change the group for the device in the container.
```
chgrp audio /dev/bus/usb/[vendorid]/[productid]
```
Note: my device (ubuntu phone) is in the audio group on the host

**Comment by fnjeneza** [comment]
The gid for the usb device can also be defined in the config of the container

**Comment by stgraber** [comment]
Ah, good to know. Not sure why the group would have to align with the host, but maybe something in the container is somehow also running as that group causing the issue.

Anyway, doesn't sound like there's anything wrong with LXD's implementation of this anymore, so closing.
