### ISSUE TITLE
`lxc network set lxdbr0 ipv6.address none` panics

### ISSUE THREAD

**Issue by OddBloke** [lxc/lxd#2785]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 17.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.9.0-11-generic
   * LXC version: 2.0.6-0ubuntu5
   * LXD version: 2.7-0ubuntu2
   * Storage backend in use: dir

# Issue description

When I run `lxc network set lxdbr0 ipv6.address none`, we get: 

```
panic: assignment to entry in nil map

goroutine 1 [running]:
panic(0x7fbdc1a89d40, 0xc42000e010)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1ad
main.(*networkCmd).doNetworkSet(0x7fbdc281ce48, 0xc4202e2120, 0x7fff0d74c2f6, 0x6, 0xc4202d04e0, 0x2, 0x2, 0x55bf219d2827, 0xc4202c2a50)
	/build/lxd-V1sHjm/lxd-2.7/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/network.go:459 +0x187
main.(*networkCmd).run(0x7fbdc281ce48, 0xc4202c2ab0, 0xc4202d04c0, 0x4, 0x4, 0x0, 0x0)
	/build/lxd-V1sHjm/lxd-2.7/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/network.go:109 +0x1d3
main.run(0x0, 0x0)
	/build/lxd-V1sHjm/lxd-2.7/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/main.go:140 +0x779
main.main()
	/build/lxd-V1sHjm/lxd-2.7/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/main.go:21 +0x39
```

This should be a decent error message.

**Comment by OddBloke** [comment]
`conjure-up` recommends running this command to disable IPv6, so that Juju doesn't use IPv6 addresses (which confuse it).

**Comment by brauner** [comment]
I think that his may have been fixed in current master. I can't really reproduce it there. Is there a possibility for you to test this?

**Comment by stgraber** [comment]
@brauner no, it's not fixed, it's what happens when you talk to an old LXD which doesn't implement that API. Fix sent.

**Comment by brauner** [comment]
@stgraber, thanks!
