### ISSUE TITLE
Upgrade from 2.0.9 to 2.9.2 hangs and results to nothing.

### ISSUE THREAD

**Issue by geodb27** [lxc/lxd#2928]
* Distribution: Ubuntu LTS
 * Distribution version: 16.04

   * Kernel version: 4.4.0-63-generic #84-Ubuntu SMP
   * LXC version: 2.9.2
   * LXD version: 2.9.2
   * Storage backend in use: dir

I went on e fresh vm, on which ubuntu lts 16.04 was installed. Launched/init lxd, copied a container from another host to this vm without any problem. Then, added the ppa to get last 2.9.2 lxd suite, and installed the last 2.9.2 version. This leads to apt-get to stay locked. An excerpt from ps -xft : 
 \_ apt-get install -y linux-generic linux-headers-generic linux-image-generic lxd lxd-client snapd ubuntu-core-launcher
  \_ /usr/bin/dpkg --status-fd 63 --configure snap-confine:amd64 ubuntu-core-launcher:amd64 ebtables:amd64 linux-image-4.4.0-64-generic:amd64 linux-image
    \_ /bin/sh /var/lib/dpkg/info/lxd.postinst configure 2.0.9-0ubuntu1~16.04.1
        \_ /bin/sh -e /usr/lib/lxd/upgrade-bridge
          \_ lxc finger --force-local

 1. Step one
Install a fresh ubuntu lts 16.04, lxd-2.0.9, have at least one container (lxd-bridge setup and functionnal, lxd_dnsmask also).
 2. Step two
Install the last 2.9.2 version of lxd tools

- [x] output of the install command on the terminal : 

Paramétrage de linux-image-generic (4.4.0.64.68) ...
Paramétrage de linux-headers-4.4.0-64 (4.4.0-64.85) ...
Paramétrage de linux-headers-4.4.0-64-generic (4.4.0-64.85) ...
Paramétrage de linux-headers-generic (4.4.0.64.68) ...
Paramétrage de linux-generic (4.4.0.64.68) ...
Paramétrage de lxd-client (2.9.2-0ubuntu1~ubuntu16.04.1~ppa1) ...
Paramétrage de lxd (2.9.2-0ubuntu1~ubuntu16.04.1~ppa1) ...
Installation de la nouvelle version du fichier de configuration /etc/init.d/lxd ...
Installation de la nouvelle version du fichier de configuration /etc/init/lxd.conf ...
Job for lxd-containers.service failed because a timeout was exceeded. See "systemctl status lxd-containers.service" and "journalctl -xe" for details.
lxd-containers.service couldn't restart.
Setting up lxd dnsmasq configuration.

Old bridge configuration detected in /etc/default/lxd-bridge, upgrading

At this stage, the terminal hang, even Ctrl+C don't do anything... I'll have to kill them all :-)

 - [x] main daemon log (/var/log/lxd.log)
lvl=info msg="LXD 2.9.2 is starting in normal mode" path=/var/lib/lxd t=2017-02-22T13:30:21+0100
lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2017-02-22T13:30:21+0100
lvl=info msg="Default uid/gid map:" t=2017-02-22T13:30:21+0100
lvl=info msg=" - u 0 100000 65536" t=2017-02-22T13:30:21+0100
lvl=info msg=" - g 0 100000 65536" t=2017-02-22T13:30:21+0100
lvl=warn msg="Storage volumes database already contains an entry for the container." t=2017-02-22T13:30:21+0100

 - [x] output of journalctl --unit lxd 

févr. 22 13:30:21 xxxxxx systemd[1]: Starting LXD - main daemon...
févr. 22 13:30:21 xxxxxx lxd[38742]: lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2017-02-22T13:30:21+0100
févr. 22 13:30:21 xxxxxxx lxd[38742]: lvl=warn msg="Storage volumes database already contains an entry for the container." t=2017-02-22T13:30:21+0100
févr. 22 13:30:21 xxxxxx lxd[38742]: error: rename /var/lib/lxd/containers/lxc-all /var/lib/lxd/storage-pools/default/containers/lxc-all: invalid cross-device link
févr. 22 13:30:21 xxxxxx systemd[1]: lxd.service: Main process exited, code=exited, status=1/FAILURE

Hope this will help to get things to work. I can undo/redo at will, this is not yet a production machine.

**Comment by brauner** [comment]
@geodb27, what storage backend are you using on this LXD instance before the upgrade?

**Comment by geodb27** [comment]
Storage backend in use: dir ;-)

**Comment by brauner** [comment]
So the problem seems to be: 

```
rename /var/lib/lxd/containers/lxc-all /var/lib/lxd/storage-pools/default/containers/lxc-all:
```

Is `/var/lib/lxd/containers` on a separate device? Hm, we can handle this in any case.

**Comment by geodb27** [comment]
You might have pointed out where the problem is....
I didn't think that this could be a problem...
As a matter of fact, I have a separate vmdk that is mounted on /var/lib/lxd/containers :
/dev/mapper/vgLXC-lv_lxc on /var/lib/lxd/containers type xfs (rw,relatime,attr2,inode64,noquota)
And /var/lib/lxd/storage-pools is consequently on another device, another vmdk on my case.

**Comment by brauner** [comment]
Well, we can handle this case I think, we need to copy instead of rename and we should have code for that.

**Comment by geodb27** [comment]
copy ? Why not use move instead of rename ?

**Comment by brauner** [comment]
Move should copy in the cross-device case to, in the other case it acts as a rename.

**Comment by brauner** [comment]
Should be addressed by https://github.com/lxc/lxd/pull/2925.

**Comment by tchwpkgorg** [comment]
I'm still seeing it with 2.0.9 -> 2.13 upgrade on Ubuntu 16.04.

Process list shows:

```
root      1598  0.0  0.0  23352  5500 pts/8    Ss+  15:02   0:00  |           \_ /usr/bin/dpkg --status-fd 48 --configure git-man:all git:amd64 lxcfs:amd64 liblxc1:amd64 lxc-common:amd64 lxd-client:amd64 lxd:amd64 python3-lxc:amd64 lxc1:amd64 lxc-templates:amd64 libpam-cgfs:amd64 libxenstore3.0:amd64 libxen-4.6:amd64 linux-crashdump:amd64 linux-libc-dev:amd64 lxd-tools:amd64 lxc:all
root      1685  0.0  0.0   8632  1624 pts/8    S+   15:02   0:00  |               \_ /bin/sh /var/lib/dpkg/info/lxd.postinst configure 2.0.9-0ubuntu1~16.04.2
root      1927  0.0  0.0   8632   836 pts/8    S+   15:02   0:00  |                   \_ /bin/sh -e /usr/lib/lxd/upgrade-bridge
root      1929  0.0  0.0 126848  9484 pts/8    Sl+  15:02   0:00  |                       \_ lxc finger --force-local
```

And terminal hangs at:

```
(...)
Setting up lxd (2.13-0ubuntu3~ubuntu16.04.1~ppa1) ...
Installing new version of config file /etc/init.d/lxd ...
Installing new version of config file /etc/init/lxd.conf ...
Job for lxd-containers.service failed because a timeout was exceeded. See "systemctl status lxd-containers.service" and "journalctl -xe" for details.
lxd-containers.service couldn't restart.
Setting up lxd dnsmasq configuration.

Old bridge configuration detected in /etc/default/lxd-bridge, upgrading
```

**Comment by brauner** [comment]
We'd need the lxd daemon log to assess whether this is storage related.

**Comment by tchwpkgorg** [comment]
This is the whole file - is it enough?

```# cat /var/log/lxd/lxd.log
lvl=info msg="Updating images" t=2017-05-16T07:05:52+0000
lvl=info msg="Done updating images" t=2017-05-16T07:05:53+0000
lvl=info msg="Expiring log files" t=2017-05-16T11:41:14+0000
lvl=info msg="Done expiring log files" t=2017-05-16T11:41:15+0000
lvl=info msg="Pruning expired images" t=2017-05-16T11:41:15+0000
lvl=info msg="Done pruning expired images" t=2017-05-16T11:41:15+0000
lvl=info msg="Updating images" t=2017-05-16T13:05:53+0000
lvl=info msg="Done updating images" t=2017-05-16T13:05:54+0000
lvl=info msg="Received 'terminated signal', exiting." t=2017-05-16T15:01:56+0000
lvl=info msg="Stopping REST API handler:" t=2017-05-16T15:01:56+0000
lvl=info msg=" - closing socket" socket=[::]:8443 t=2017-05-16T15:01:56+0000
lvl=info msg=" - skipping socket-activated socket" socket=/var/lib/lxd/unix.socket t=2017-05-16T15:01:56+0000
lvl=info msg="Closing the database" t=2017-05-16T15:01:57+0000
lvl=info msg="Stopping /dev/lxd handler" t=2017-05-16T15:01:57+0000
lvl=info msg="Stopped /dev/lxd handler" t=2017-05-16T15:01:57+0000
lvl=info msg="Saving simplestreams cache" t=2017-05-16T15:01:57+0000
lvl=info msg="Saved simplestreams cache" t=2017-05-16T15:01:57+0000
lvl=info msg="LXD 2.13 is starting in normal mode" path=/var/lib/lxd t=2017-05-16T15:02:30+0000
lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2017-05-16T15:02:30+0000
lvl=info msg="Kernel uid/gid map:" t=2017-05-16T15:02:30+0000
lvl=info msg=" - u 0 0 4294967295" t=2017-05-16T15:02:30+0000
lvl=info msg=" - g 0 0 4294967295" t=2017-05-16T15:02:30+0000
lvl=info msg="Configured LXD uid/gid map:" t=2017-05-16T15:02:30+0000
lvl=info msg=" - u 0 100000 65536" t=2017-05-16T15:02:30+0000
lvl=info msg=" - g 0 100000 65536" t=2017-05-16T15:02:30+0000
lvl=info msg="Creating BTRFS storage pool \"default\"." t=2017-05-16T15:02:31+0000
lvl=info msg="Created BTRFS storage pool \"default\"." t=2017-05-16T15:03:19+0000
lvl=info msg="LXD 2.13 is starting in normal mode" path=/var/lib/lxd t=2017-05-16T15:12:30+0000
lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2017-05-16T15:12:30+0000
lvl=info msg="Kernel uid/gid map:" t=2017-05-16T15:12:31+0000
lvl=info msg=" - u 0 0 4294967295" t=2017-05-16T15:12:31+0000
lvl=info msg=" - g 0 0 4294967295" t=2017-05-16T15:12:31+0000
lvl=info msg="Configured LXD uid/gid map:" t=2017-05-16T15:12:31+0000
lvl=info msg=" - u 0 100000 65536" t=2017-05-16T15:12:31+0000
lvl=info msg=" - g 0 100000 65536" t=2017-05-16T15:12:31+0000
lvl=warn msg="Incorrectly applied \"storage_api\" patch. Skipping storage pool initialization as it might be corrupt." t=2017-05-16T15:12:31+0000
lvl=warn msg="Database already contains a valid entry for the storage pool: default." t=2017-05-16T15:12:31+0000
lvl=info msg="LXD 2.13 is starting in normal mode" path=/var/lib/lxd t=2017-05-16T15:25:12+0000
lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2017-05-16T15:25:12+0000
lvl=info msg="Kernel uid/gid map:" t=2017-05-16T15:25:12+0000
lvl=info msg=" - u 0 0 4294967295" t=2017-05-16T15:25:12+0000
lvl=info msg=" - g 0 0 4294967295" t=2017-05-16T15:25:12+0000
lvl=info msg="Configured LXD uid/gid map:" t=2017-05-16T15:25:12+0000
lvl=info msg=" - u 0 100000 65536" t=2017-05-16T15:25:12+0000
lvl=info msg=" - g 0 100000 65536" t=2017-05-16T15:25:12+0000
```

**Comment by tchwpkgorg** [comment]
Also - I have a symbolic link, /var/lib/lxd -> /srv/lxd - this might break something?

**Comment by brauner** [comment]
It might very well. Can you interact with the daemon? Meaning, does e.g. `lxc info` work?

**Comment by tchwpkgorg** [comment]
All lxc commands seem to hang as well.

**Comment by brauner** [comment]
So, symlinking `/var/lib/lxd` is something we suggest not do! Instead, a bind-mount should be used in such cases.
Can you remove the symlink and then do

    mount -B /srv/lxd /var/lib/lxd

and try to start the daemon again and report back, please?

Also, what storage backend did you use on the original LXD instance?

**Comment by tchwpkgorg** [comment]
Storage backend was dir (on btrfs).

I'll get rid of the symlink and will try again.

**Comment by brauner** [comment]
@tchwpkgorg, make sure to stop all hanging lxd's first.

dir on btrfs? That storage combination sounds strange.

**Comment by tchwpkgorg** [comment]
> dir on btrfs? That storage combination sounds strange.

I mean, /srv was mounted as a btrfs filesystem, and /srv/lxd symlinked to /var/lib/lxd. I'll get that changed to bind mounts.

**Comment by tchwpkgorg** [comment]
It works now after getting rid of the symlink.
