### ISSUE TITLE
LXD dnsmasq is retuning the wrong ips

### ISSUE THREAD

**Issue by adilbaig** [lxc/lxd#3978]
Github issues are used for bug reports. For support questions, please use [our forum](https://discuss.linuxcontainers.org).

Please fill the template below as it will greatly help us track down your issue and reproduce it on our side.  
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-97-generic
   * LXC version: (driver_version: 2.0.7)
   * LXD version: 2.14
   * Storage backend in use: zfs 

# Issue description
LXD's dnsmasq is returning outdated IP addresses for containers. As a result we are not able to proxy Apache requests to the correct containers.

I have an apache setup that forwards to containers. This is a sample vhost
````
<VirtualHost *:80>
    ...
    ProxyPreserveHost On
    ProxyPass / http://symfony-cli.lxd:80/
    ProxyPassReverse / http://symfony-cli.lxd:80/
    ...
</VirtualHost>
````
A dnsmasq instance on the host machine forwards `.lxd` requests to LXD's dnsmasq. Unfortunately, that is returning the wrong ips. I traced it down to an outdated mapping in the `/var/lib/lxd/networks/lxdbr0/dnsmasq.hosts` file.

# Steps to reproduce
Not sure. I only noticed the discrepancy. I believe when we stop and start containers (that have ips assigned via LXDs DHCP) and the IPs get reassigned, the dnsmasq is not keeping up.

Also, it looks like it only affects containers that have been `copy`d from another container.

# Information to attach
````
ubuntu@compute01:~$ lxc list symfony
+-------------------------+---------+-------------------+------+------------+-----------+
|          NAME           |  STATE  |       IPV4        | IPV6 |    TYPE    | SNAPSHOTS |
+-------------------------+---------+-------------------+------+------------+-----------+
| symfony-cli             | RUNNING | 10.0.1.2 (eth1)   |      | PERSISTENT | 1         |
+-------------------------+---------+-------------------+------+------------+-----------+
| symfony-cli-adil        | RUNNING | 10.0.1.217 (eth0) |      | PERSISTENT | 0         |
+-------------------------+---------+-------------------+------+------------+-----------+
| symfony-cli-adil-prices | RUNNING | 10.0.1.201 (eth0) |      | PERSISTENT | 0         |
+-------------------------+---------+-------------------+------+------------+-----------+
| symfony-cli-arshad      | RUNNING | 10.0.1.44 (eth0)  |      | PERSISTENT | 0         |
+-------------------------+---------+-------------------+------+------------+-----------+
| symfony-cli-movements   | RUNNING | 10.0.1.88 (eth0)  |      | PERSISTENT | 1         |
+-------------------------+---------+-------------------+------+------------+-----------+
| symfony-cli-staging     | RUNNING | 10.0.1.39 (eth0)  |      | PERSISTENT | 0         |
+-------------------------+---------+-------------------+------+------------+-----------+
ubuntu@compute01:~$ sudo cat /var/lib/lxd/networks/lxdbr0/dnsmasq.hosts
...
00:16:3e:81:5b:9e,id:*,10.0.1.2,symfony-cli
00:16:3e:95:db:3f,id:*,10.0.1.217,symfony-cli-adil
00:16:3e:86:5b:b4,id:*,10.0.1.217,symfony-cli-adil-prices
00:16:3e:39:09:f5,id:*,10.0.1.217,symfony-cli-arshad
00:16:3e:d4:21:5b,symfony-cli-movements
00:16:3e:6b:ae:2f,id:*,10.0.1.217,symfony-cli-staging
....
````

**Comment by stgraber** [comment]
This has been fixed in 2.18 by changing a bunch of the logic to control dnsmasq. It's not airways perfect because dnsmasq's file watch are inherently racy but should be unnoticeable.

**Comment by adilbaig** [comment]
I updated it to 2.18, restarted the server and i'm still getting the wrong ip

````
ubuntu@compute01:~$ lxd --version
2.18
ubuntu@compute01:~$ lxc --version
2.18
ubuntu@compute01:~$ sudo service lxd restart
ubuntu@compute01:~$ sudo kill -SIGHUP 94842 # kill dnsmasq
ubuntu@compute01:~$ lxc list symfony-cli-staging
+---------------------+---------+------------------+------+------------+-----------+
|        NAME         |  STATE  |       IPV4       | IPV6 |    TYPE    | SNAPSHOTS |
+---------------------+---------+------------------+------+------------+-----------+
| symfony-cli-staging | RUNNING | 10.0.1.39 (eth0) |      | PERSISTENT | 0         |
+---------------------+---------+------------------+------+------------+-----------+
ubuntu@compute01:~$ ping symfony-cli.lxd
PING symfony-cli.lxd (10.0.1.39) 56(84) bytes of data. #WRONG IP!
64 bytes from 10.0.1.39: icmp_seq=1 ttl=64 time=0.038 ms
64 bytes from 10.0.1.39: icmp_seq=2 ttl=64 time=0.051 ms
64 bytes from 10.0.1.39: icmp_seq=3 ttl=64 time=0.055 ms
64 bytes from 10.0.1.39: icmp_seq=4 ttl=64 time=0.039 ms
64 bytes from 10.0.1.39: icmp_seq=5 ttl=64 time=0.035 ms
64 bytes from 10.0.1.39: icmp_seq=6 ttl=64 time=0.028 ms
^C
--- symfony-cli.lxd ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5000ms
rtt min/avg/max/mdev = 0.028/0.041/0.055/0.009 ms
ubuntu@compute01:~$ ping symfony-cli-staging.lxd
ping: unknown host symfony-cli-staging.lxd #NO IP
````
Am i missing something?

**Comment by stgraber** [comment]
@adilbaig can you post "lxc network show lxdbr0"?

**Comment by adilbaig** [comment]
````
ubuntu@compute01:~$ lxc network show lxdbr0
config:
  dns.domain: lxd
  dns.mode: managed
  ipv4.address: 10.0.1.1/24
  ipv4.dhcp.ranges: 10.0.1.2-10.0.1.254
  ipv4.nat: "true"
  ipv6.address: none
  raw.dnsmasq: conf-file=/home/ubuntu/stockopedia-lxd-dnsmasq.conf
description: ""
name: lxdbr0
type: bridge
used_by:
- /1.0/containers/blah
- /1.0/containers/devop-tools
- /1.0/containers/polished-thrush
- /1.0/containers/python-adil
- /1.0/containers/python-arshad
- /1.0/containers/python-live
- /1.0/containers/python-staging
- /1.0/containers/symfony-cli
- /1.0/containers/symfony-cli-adil
- /1.0/containers/symfony-cli-arshad
- /1.0/containers/symfony-cli-movements
- /1.0/containers/symfony-cli-staging
managed: true
````

**Comment by adilbaig** [comment]
@stgraber I believe the issue was related to setting static Ips to the eth0 device of the container, which i didn't notice at the time. (`lxc config device show mycontainer`). Once I deleted the device dnsmasq figured out the routing.
