### ISSUE TITLE
Lxd container stop automatically and cannot longer restart. Help needed!

### ISSUE THREAD

**Issue by HW-Siew** [lxc/lxd#4408]
# Required information

 * Distribution: ubuntu
 * Distribution version: 16.04 
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.13.0-1011-gcp
   * LXC version: 3.0.0
   * LXD version: 3.0.0
   * Storage backend in use: zfs

# Issue description

Out of sudden, most of my container stop and cannot restart anymore. All show the same error message

```
lxc 20180404134112.574 ERROR    lxc_conf - conf.c:run_buffer:347 - Script exited with status 1
lxc 20180404134112.575 ERROR    lxc_start - start.c:lxc_init:815 - Failed to run lxc.hook.pre-start for container "web102"
lxc 20180404134112.575 ERROR    lxc_start - start.c:__lxc_start:1832 - Failed to initialize container "web102"
lxc 20180404134112.575 ERROR    lxc_container - lxccontainer.c:wait_on_daemonized_start:815 - No such file or directory - Failed to receive the container state
```

**Comment by stgraber** [comment]
That's most likely our favorite ZFS bug... the good news is that this is finally getting fixed upstream.
Can you run:

   grep containers/NAME /proc/*/mountinfo

Where NAME is the name of one such container?

**Comment by HW-Siew** [comment]
Hi @stgraber, thank you so much for the prompt reply.

this is the output i got.

`/proc/2613/mountinfo:175 134 0:63 / /var/snap/lxd/common/lxd/storage-pools/lxd/containers/web102 rw,relatime - zfs lxd/containers/web102 rw,xattr,noacl`

**Comment by stgraber** [comment]
@HW-Siew cool, so doing:

    nsenter -t 2613 -n
        umount /var/snap/lxd/common/lxd/storage-pools/lxd/containers/web102
        exit
    lxc start web102

Should fix that particular container.
You should be able to perform the umounts for all the affected containers from that nsenter shell.

**Comment by HW-Siew** [comment]
Hi @stgraber , no luck... :( 

I  run

```
> sudo nsenter -t 2613 -n
> umount /var/snap/lxd/common/lxd/storage-pools/lxd/containers/web102
```

it output 

`umount: /var/snap/lxd/common/lxd/storage-pools/lxd/containers/web102: not mounted`

and i tried again lxc start web102. it still doesnt work and show the same error.

**Comment by stgraber** [comment]
Oh, doh, sorry, use `nsenter -t 2613 -m`, `-n` is for network namespace, `-m` is for mount namespace.

**Comment by HW-Siew** [comment]
Oh my... Thanks !!! @stgraber , It is finally working! Very much appreciated your help!

If I may ask further, anything I can do to prevent this from happening again?

**Comment by stgraber** [comment]
Not much unfortunately. We do have a ZFS fix that will be included in the Ubuntu kernels and is being reviewed upstream, so hopefully this issue will soon be a thing of the past...

It looks like the usual culprint when it comes to keeping references to those mounts is lxcfs so I'll see if there's something I can do there to have it cleanup its mount table prior to startup, that may help.

**Comment by HW-Siew** [comment]
Thanks !
