### ISSUE TITLE
lxc list when not on default project results in Error: Not Found

### ISSUE THREAD

**Issue by zacksiri** [lxc/lxd#5192]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.10
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.18.0-1002-gcp
   * LXC version: 3.0.2
   * LXD version: "3.6"
   * Storage backend in use: zfs

# Issue description

When I try to list containers when i'm not on a default project I get Error: Not Found

# Steps to reproduce

 1. create a container in default
 2. create a project
 3. create a new container in the new project
 4. lxc list when on the new project

**Comment by zacksiri** [comment]
Actually It was while I was running another build using packer. seems lxd can't list container in the same project if packer build is running.

**Comment by zacksiri** [comment]
I got this error when using packer build on a container when the project is not default 

```bash
app-image output will be in this color.

==> app-image: Creating container...
==> app-image: Provisioning with shell script: initialize.sh
==> app-image: Unregistering and deleting deleting container...
Build 'app-image' errored: Retryable error: Error uploading script: exit status 1
```

**Comment by cyberwillis** [comment]
Why do you have unmatched version between LXC and LXD ?
LXC version: 3.0.2
LXD version: "3.6"

**Comment by zacksiri** [comment]
I think that’s how it’s supposed to be, I think the lxd in this case is the container engine underneath not the client. Try running lxc info, these version numbers came from there.

**Comment by cyberwillis** [comment]
Yes, my bad I thought about the output of lxc --version command instead. 
Btw actually my versions LXC and LXD are the lastest commit from the master branches,  LXC (3.0.0 - 65322e5) and LXD (3.6 - 2e0a016). Ironically LXC 3.0.2 is a branch of two months ago, so I assume my version is beyond what you have installed now, and I couldn't find any error.

**Comment by cyberwillis** [comment]
I believe the big question is, what is the meaning of this lines if ommited ?
-c features.images=false (inherts from default project)
-c features.profiles=false (inherts from default project)

To me appear if I omit it is because I need to create my own default profile so I don't need to count it will cause a error if I start without one ! If I desire to have a default or the same of my **default** project I need to inherit from it !

**Comment by cyberwillis** [comment]
I realized your error is not the same as I replicated so I decided to creates another thread about that. 
https://github.com/lxc/lxd/issues/5194

**Comment by stgraber** [comment]
I just released an update to stable snap user which fixes a number of issues with projects including this one. Please run `snap refresh lxd` and try again, your container should then appear.

**Comment by stgraber** [comment]
(One issue which we fixed and matches those symptoms here was about the /1.0/containers ?recursion listing API having bad project filtering in some listing modes)

**Comment by zacksiri** [comment]
@stgraber not sure if I'm running the latest one with the fix but the problem still persists, I also can't console into a container in a project.

**Comment by freeekanayaka** [comment]
I confirm this bug. I can reproduce it with the steps indicated in the issue description. I'll fix it.

@zacksiri regarding the other issue you mention, what do you mean exactly by "I can't console into a container in a project" ?

**Comment by zacksiri** [comment]
@freeekanayaka when I create a container under a project that's not default, I type `lxc console test` and i get an error 

```
➜  ~ lxc project switch upmaru
➜  ~ lxc launch images:alpine/3.8 test
Creating test
Starting test
➜  ~ lxc list
+------+---------+------------------+------+------------+-----------+-------------------------+
| NAME |  STATE  |       IPV4       | IPV6 |    TYPE    | SNAPSHOTS |        LOCATION         |
+------+---------+------------------+------+------------+-----------+-------------------------+
| test | RUNNING | 240.7.0.2 (eth0) |      | PERSISTENT |           | artello-foundation-hv2v |
+------+---------+------------------+------+------------+-----------+-------------------------+
➜  ~ lxc console test
To detach from the console, press: <ctrl>+a q
Error: Failed running forkconsole: "container is not running: \"test\""
Error: exit status 1
```

**Comment by freeekanayaka** [comment]
Sorry, actually I retract. I can't reproduce it, I was doing it wrong. I have this test which passes:

```bash
# Use containers in a project.
test_issue_5192() {
  ensure_import_testimage

  # Create a container in the default project
  lxc init testimage c1

  # Create a project and switch to it
  lxc project create foo
  lxc project switch foo

  deps/import-busybox --project foo --alias testimage

  # Add a root device to the default profile of the project
  lxc profile device add default root disk path="/" pool="lxdtest-$(basename "${LXD_DIR}")"

  # Create a container in the project
  lxc init testimage c1

  # The container is listed when using this project
  lxc list
  lxc delete c1
  lxc image delete testimage

  # Delete the project
  lxc project delete foo
}
```

@zacksiri does the test above reflect what you are doing?

**Comment by zacksiri** [comment]
**I can list the container inside the project now**, it's just other operations, like trying to console into the container, is a problem, or when I run packer, because packer **pretty much hangs leaving the container in a 'stuck' state making lxc list not work**.

if I launch a container it launches fine, and i can run list to see it. but when I run `lxc console test` i get the error above.

**Comment by freeekanayaka** [comment]
I confirm the console bug, will provide a fix.

I'm not sure exactly what issues are you hitting with packer tho (if they are related to the lxc console one, or they are separate).

**Comment by freeekanayaka** [comment]
I've reopened the issue, although it has basically changed, since it's now about ```lxc console```.

**Comment by zacksiri** [comment]
@freeekanayaka regards to packer it’s probably making calls using the client that is broken when using a project so I’m guess fixing those calls to work with projects will fix issues with packer commands like exec, pushing files etc... I will test out the different commands and let you know what works and what doesn’t.
