### ISSUE TITLE
lxd profile intermittently fails to apply

### ISSUE THREAD

**Issue by hmlanigan** [lxc/lxd#5496]
# Required information

 * Distribution: ubuntu
 * Distribution version: 18.10
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.18.0-15-generic
   * LXC version: 3.10
   * LXD version: 3.10
   * Storage backend in use: btrfs | dir

# Issue description

Juju has a new feature in 2.5 to allow for adding a lxd profile file inside a charm, to be applied to a lxd machine when the charm is deployed.

Recently we've noticed that profiles fail to add to a machine intermittently, e.g. of 6 machines, 4 or 5 might add the profile but 1 fails.  In this case juju is creating the container, then adding the profile.  If juju creates the container with the profile, this generally doesn't happen.

I'm using the lxd snap with the stable channel on Cosmic. This appears to be newer behavior, since the end of last year.

# Steps to reproduce

- examples with lxc cli, including profile contents: https://pastebin.canonical.com/p/zXkQSPpMrH/
- example with juju and the bundle used to reproduce: https://paste.ubuntu.com/p/7Fk7dC96Gt/
- example with juju switch machines deployed with the profile and no issues: https://paste.ubuntu.com/p/5wqrSFMwZG/

# Information to attach

- d.log with debugging enabled: http://people.canonical.com/~heather/lxd/lxd.log
- syslog: http://people.canonical.com/~heather/lxd/syslog

**Comment by stgraber** [comment]
Tracked this down to a liblxc bug in the mount function which was preventing over-mounting in this case.
We've just merged a fix now in liblxc and have cherry-picked it into the snap. A new stable snap should be rolling out in the next 24h with the fix.

**Comment by stgraber** [comment]
That's irrelevant, the fix in liblxc only applies to liblxc 3.1 and higher, 3.0.x doesn't have this piece of code.

**Comment by hmlanigan** [comment]
I'm still experiencing this issue.  Last attempt was with the candidate snap, I've also tried the stable and edge snaps with the same result.  Is there a different snap I should try?

**Comment by stgraber** [comment]
Looks like the fix doesn't work as well as expected, I submitted a follow-up fix which we're testing now, snap should get updated later today.

**Comment by stgraber** [comment]
@hmlanigan Current stable snap should be fine, seems fine here (though I had to remove the USB and GPU devices as I have neither of those here)

**Comment by hmlanigan** [comment]
@stgraber,  Works for me now with the new stable snap.  Thank you!
