### ISSUE TITLE
Issue with Copy containers with BTRFS storage and docker

### ISSUE THREAD

**Issue by rudiservo** [lxc/lxd#6607]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.0
   * LXC version: 3.18
   * LXD version: 3.18
   * Storage backend in use: BTRFS

# Issue description
I believe that there is maybe and issue with dockers and move or copy containers.
if I try do delete any docker container inside a copied lxd container I get this error

Error response from daemon: container b3865b317cffcf43a11a4b56b065798d1da43e210ac486a5d64562421886c441: driver "btrfs" failed to remove root filesystem: Failed to destroy btrfs snapshot /var/lib/docker/btrfs/subvolumes for ba2b6736e6751fe1e30a519c7cb5984fc51d97e3bb3ea92046c2faee6c93fc55: invalid argument

mount output
/dev/nvme1n1 on / type btrfs (rw,relatime,compress=zstd,ssd,space_cache,user_subvol_rm_allowed,subvolid=480,subvol=/lxd/containers/stg/rootfs)
/dev/nvme1n1 on /var/lib/docker/btrfs type btrfs (rw,relatime,compress=zstd,ssd,space_cache,user_subvol_rm_allowed,subvolid=480,subvol=/lxd/containers/stg/rootfs/var/lib/docker/btrfs)

Am I doing anything wrong?

**Comment by stgraber** [comment]
So the main underlying problem has been fixed with the new storage driver implementation.
I believe we had a bug which was causing us to incorrectly select rsync in some btrfs copy cases, making it so that the copy would not be using subvolumes. This would explain the error you're getting.

To recover on systems prior to LXD 3.19 (which will have the new implementation), your best bet is to manually re-create those as subvolumes or if you only really care about deleting the thing, I suspect a good old `rm -Rf` may do the trick too.

Closing as code path described in this issue has or is going away prior to next release.

**Comment by rudiservo** [comment]
OK thanks.
I dont mind redoing everything, just trying to accelerate development with gigantic databases and programs by cloning lxd containers instead of redoing everything for docker, it just goes in the lxd.
Dont kill me! :laughing:

**Comment by rudiservo** [comment]
@stgraber Hi sorry but I think we might have to reopen this issue or I am doing something wrong, I have 3.19 but the issue persists but with different messaging.

I know you must be busy has hell with the new release, no hurries but either open it again or should I create a new one?

Creating webdevkit_mysql_1 ... 
Creating webdevkit_mysql_1 ... error

ERROR: for webdevkit_mysql_1  Cannot create container for service mysql: stat /var/lib/docker/btrfs/subvolumes/5a06304b5921b85a03b4d6d69df3f23ac71e10ee217cd85cb3688015415dc19b: no such file or directory

ERROR: for mysql  Cannot create container for service mysql: stat /var/lib/docker/btrfs/subvolumes/5a06304b5921b85a03b4d6d69df3f23ac71e10ee217cd85cb3688015415dc19b: no such file or directory
ERROR: Encountered errors while bringing up the project.
