### ISSUE TITLE
`lxc exec` hangs - how to troubleshoot?

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#764]
I've initialized container and trying to apt-get install stuff into it making snapshots on the way. Sometimes the `lxc exec contain -- apt-get install git` just hangs with no output and not responding to Ctrl-C etc. How to figure out what happens?

**Comment by tych0** [comment]
On Sun, Jun 14, 2015 at 12:32:56PM -0700, anatoly techtonik wrote:
> I've initialized container and trying to apt-get install stuff into it making snapshots on the way. Sometimes the `lxc exec contain -- apt-get install git` just hangs with no output and not responding to Ctrl-C etc. How to figure out what happens?

I think this was just fixed with
cf71a229433751b5faa567e924a636fdff8dcb5a, if you build with that it
should work.

Tycho

**Comment by stgraber** [comment]
Are you running with Go 1.4 by any chance?

**Comment by stgraber** [comment]
@tych0 my commit indeed fixes a race in there, though we still have the problem that multi-threaded unix communication seem to be busted on Go 1.4 for some reason.

**Comment by techtonik** [comment]
@stgraber strange thing. `go version` shows `go version xgcc (Ubuntu 4.9.1-0ubuntu1) 4.9.1 linux/386`. I don't know which version of Go lang is this.

**Comment by stgraber** [comment]
Oh, looks like you're running gccgo then instead of golang-go. That version is 1.4 from gccgo.

I'd recommend you uninstall any gccgo.* package from your system and instead install golang-go. That compiler tends to be better on x86, especially for memory consumption.

For our own packages we only use gccgo for architectures which golang-go doesn't support, so currently arm64, powerpc and ppc64el.

**Comment by techtonik** [comment]
`gccgo-go` is the only alternative that is proposed for missing `go` binary. Should it be fixed?

**Comment by techtonik** [comment]
But it seems irrelevant. I removed gccgo.* and LXC still works. I am using LXC from PPA.

**Comment by stgraber** [comment]
Odd, here I definitely have golang-go providing the go command.

**Comment by techtonik** [comment]
Why odd? LXC is compiled into binary and doesn't need go, no?

As for proposal, filled https://bugs.launchpad.net/ubuntu/+source/command-not-found/+bug/1465705

**Comment by stgraber** [comment]
I was referring to the fact that gccgo-go is the only alternative for go. That shouldn't be the case as golang-go also provides it.

**Comment by rcj4747** [comment]
I've build from 3efd3a1b44c5c4603d6150b2f2266e6e940d04ec and recreated on vivid.  My very temporary solution (which still occasionally fails) is:

sudo systemctl restart lxd
sleep 1
lxc stop vivid
sleep 1
lxc start vivid
sleep 1
lxc exec vivid /bin/bash

I build with golang-go in vivid per the instructions in README.md.

**Comment by stgraber** [comment]
The fix for this was pushed last week but the issue wasn't closed. Doing so now.
